# Generated by Django 5.2.4 on 2025-09-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_nofications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другое')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user_images/person.png', upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
