# Generated by Django 5.2.4 on 2025-09-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_shop_sizes_news_views_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
